// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHK00QTsRbXgFx4pTK2ErSuS5sVbUjNvE',
    appId: '1:123287430233:web:4d85a8be603077a9ad7d48',
    messagingSenderId: '123287430233',
    projectId: 'findboarding-378601',
    authDomain: 'findboarding-378601.firebaseapp.com',
    storageBucket: 'findboarding-378601.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewjZYI9VvOCagHdC5_Ia3E_XsoF9ElJc',
    appId: '1:123287430233:android:90f39139660cb101ad7d48',
    messagingSenderId: '123287430233',
    projectId: 'findboarding-378601',
    storageBucket: 'findboarding-378601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtjy3YkVk9OcJyoi3D7riBaOnKA_gVnsg',
    appId: '1:123287430233:ios:c34d9c5da257bc38ad7d48',
    messagingSenderId: '123287430233',
    projectId: 'findboarding-378601',
    storageBucket: 'findboarding-378601.appspot.com',
    iosClientId: '123287430233-sbhprqtgkrakoolsl914afk677m2q1tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ttt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtjy3YkVk9OcJyoi3D7riBaOnKA_gVnsg',
    appId: '1:123287430233:ios:cead71f09255d67fad7d48',
    messagingSenderId: '123287430233',
    projectId: 'findboarding-378601',
    storageBucket: 'findboarding-378601.appspot.com',
    iosClientId: '123287430233-tnclvc3ofjggs3vd5pts4igmp26hfbco.apps.googleusercontent.com',
    iosBundleId: 'com.example.ttt.RunnerTests',
  );
}
